---
title: "AHEaD Simulated Data R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(tidyverse)
```

Reading in the data
```{r}
data <- read.csv("AHEaD_simulated_data.csv")
print(data)
```

create a dummy variable for female patients
```{r}
data$female = ifelse(data$sex == 'Female', 1,0)
```



```{r}
summary(data)
```

Sex - frequency and percentage 
```{r}
w = table(data$sex)
t = as.data.frame(w)
t$prop = prop.table(w)
t
```
Ethnicity frequency and percentage 
```{r}
w = table(data$ethnicity)
t = as.data.frame(w)
t$prop = prop.table(w)
t
```

Average, median, and standard deviation of serum creatinine values (Asian patients)
```{r}
aggregate(Sr_Cr~Asian, mean, data=data)
aggregate(Sr_Cr~Asian, median, data=data)
aggregate(Sr_Cr~Asian, sd, data=data)
```

Boxplots of Sr_Cr by ethnicity
https://r-graph-gallery.com/89-box-and-scatter-plot-with-ggplot2.html

```{r}
data %>%
  ggplot( aes(x=ethnicity, y=Sr_Cr, fill=ethnicity)) +
    geom_boxplot() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Sr_Cr by ethnicity") +
    xlab("Ethnicity") + ylab("Serum Creatinine")
```

Histogram of Sr_Cr by sex
https://r-graph-gallery.com/histogram_several_group.html

```{r}
data %>%
  ggplot( aes(x=Sr_Cr, fill=sex)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080")) +
    labs(fill="")

```

